# ___       ________  ________  _________        ________  ___  __        ___    ___      ___       __   ________  ________  ________      
# |\  \     |\   __  \|\   ____\|\___   ___\     |\   ____\|\  \|\  \     |\  \  /  /|    |\  \     |\  \|\   __  \|\   __  \|\   ____\     
# \ \  \    \ \  \|\  \ \  \___|\|___ \  \_|     \ \  \___|\ \  \/  /|_   \ \  \/  / /    \ \  \    \ \  \ \  \|\  \ \  \|\  \ \  \___|_    
#  \ \  \    \ \  \\\  \ \_____  \   \ \  \       \ \_____  \ \   ___  \   \ \    / /      \ \  \  __\ \  \ \   __  \ \   _  _\ \_____  \   
#   \ \  \____\ \  \\\  \|____|\  \   \ \  \       \|____|\  \ \  \\ \  \   \/  /  /        \ \  \|\__\_\  \ \  \ \  \ \  \\  \\|____|\  \  
#    \ \_______\ \_______\____\_\  \   \ \__\        ____\_\  \ \__\\ \__\__/  / /           \ \____________\ \__\ \__\ \__\\ _\ ____\_\  \ 
#     \|_______|\|_______|\_________\   \|__|       |\_________\|__| \|__|\___/ /             \|_________|\|__|\|__|\|__|\|__|\_________\___
#                        \|_________|               \|_________|         \|___|/                                                \|_________|
#                                                                                                                                           
# Config version: 2.4.24                                                                                                                             
# Plugin developed by Losted
key: ''
database:
 # Database types: MySQL | SQLite
 name: SQLite
 # MySQL connection data
 host: localhost
 port: 3306
 dbname: server
 username: root
 password: ''
# Server Modes: MULTI_ARENA, LOBBY (Lobby for Bungee Arena), ARENA (Arena for Bungee Lobby)
servermode: MULTI_ARENA